### ISSUE TITLE
beta function chokes if factor is used in formula

### ISSUE THREAD

**Issue by csrabak** [cran/reghelper#2]
I'm trying to reproduce the computations as shown in [Standardized Coefficients in Logistic Regression](https://www3.nd.edu/~rwilliam/stats3/L04.pdf).

dados <- read.dta("http://www3.nd.edu/statafiles/glm-logit.dta")

(dados.glm <- glm(grade ~ gpa + tuce + factor(psi), data=dados, family=binomial))
> beta(dados.glm)
Error in factor(psi) : object 'psi' not found

Since the syntax of glm allows having all sort of operations in the IVs including factor(), I think this is bug deserves further investigation

Regards,

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!
